name: rehber_sistem
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.1
  http: ^1.3.0
  image_picker: ^1.1.2
  location: ^8.0.0
  camera: ^0.11.1
  image: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
